
// Sample data
const SampleRecipes = [
  {
    id: "rec_101",
    name: "Paneer Butter Masala",
    cuisine: "Indian",
    isVegetarian: true,
    prepTimeMinutes: 40,
    ingredients: ["paneer", "tomato", "cream", "butter", "spices"],
    difficulty: "medium",
    instructions: "Step 1: Heat butter in a pan. Step 2: Add tomatoes and cook until soft. Step 3: Add cream and paneer. Step 4: Simmer for 10 minutes.",
    tags: ["dinner", "rich", "party"]
  },
  {
    id: "rec_102",
    name: "Margherita Pizza",
    cuisine: "Italian",
    isVegetarian: true,
    prepTimeMinutes: 30,
    ingredients: ["dough", "tomato sauce", "mozzarella", "basil", "olive oil"],
    difficulty: "easy",
    instructions: "Step 1: Roll out dough. Step 2: Spread sauce. Step 3: Add cheese and basil. Step 4: Bake at 450°F for 12 minutes.",
    tags: ["lunch", "classic", "quick"]
  },
  {
    id: "rec_103",
    name: "Chicken Tikka Masala",
    cuisine: "Indian",
    isVegetarian: false,
    prepTimeMinutes: 60,
    ingredients: ["chicken", "yogurt", "tomato", "cream", "spices"],
    difficulty: "medium",
    instructions: "Step 1: Marinate chicken in yogurt and spices. Step 2: Grill chicken pieces. Step 3: Make tomato-cream sauce. Step 4: Combine and simmer.",
    tags: ["dinner", "spicy", "popular"]
  },
  {
    id: "rec_104",
    name: "Pasta Carbonara",
    cuisine: "Italian",
    isVegetarian: false,
    prepTimeMinutes: 25,
    ingredients: ["pasta", "eggs", "bacon", "parmesan", "black pepper"],
    difficulty: "easy",
    instructions: "Step 1: Cook pasta. Step 2: Fry bacon. Step 3: Mix eggs and cheese. Step 4: Combine all with pasta water.",
    tags: ["dinner", "creamy", "quick"]
  },
  {
    id: "rec_105",
    name: "Sushi Rolls",
    cuisine: "Japanese",
    isVegetarian: false,
    prepTimeMinutes: 60,
    ingredients: ["rice", "nori", "salmon", "cucumber", "soy sauce"],
    difficulty: "hard",
    instructions: "Prepare rice, layer over nori, place fillings, roll and slice.",
    tags: ["seafood", "healthy", "traditional"]
},
{
    id: "rec_106",
    name: "Falafel Wrap",
    cuisine: "Middle Eastern",
    isVegetarian: true,
    prepTimeMinutes: 35,
    ingredients: ["chickpeas", "tahini", "garlic", "pita", "lettuce"],
    difficulty: "medium",
    instructions: "Blend chickpeas, fry balls, wrap with veggies and tahini.",
    tags: ["streetfood", "protein-rich", "lunch"]
},
{
    id: "rec_107",
    name: "Beef Stroganoff",
    cuisine: "Russian",
    isVegetarian: false,
    prepTimeMinutes: 45,
    ingredients: ["beef", "mushrooms", "onion", "cream", "noodles"],
    difficulty: "medium",
    instructions: "Cook beef, add veggies and cream, serve over noodles.",
    tags: ["creamy", "comfort-food", "dinner"]
},
{
    id: "rec_108",
    name: "Avocado Toast",
    cuisine: "American",
    isVegetarian: true,
    prepTimeMinutes: 10,
    ingredients: ["bread", "avocado", "salt", "pepper", "olive oil"],
    difficulty: "easy",
    instructions: "Toast bread, mash avocado, spread and season.",
    tags: ["breakfast", "quick", "healthy"]
},
{
    id: "rec_109",
    name: "Thai Green Curry",
    cuisine: "Thai",
    isVegetarian: false,
    prepTimeMinutes: 40,
    ingredients: ["chicken", "coconut milk", "green curry paste", "basil"],
    difficulty: "medium",
    instructions: "Cook curry paste, add coconut milk and chicken, simmer with herbs.",
    tags: ["spicy", "aromatic", "dinner"]
},
{
    id: "rec_110",
    name: "Greek Salad",
    cuisine: "Greek",
    isVegetarian: true,
    prepTimeMinutes: 15,
    ingredients: ["cucumber", "tomato", "olives", "feta cheese", "olive oil"],
    difficulty: "easy",
    instructions: "Chop veggies, mix with dressing and feta.",
    tags: ["healthy", "refreshing", "summer"]
},
{
    id: "rec_111",
    name: "Chocolate Brownies",
    cuisine: "American",
    isVegetarian: true,
    prepTimeMinutes: 35,
    ingredients: ["cocoa", "flour", "butter", "sugar", "eggs"],
    difficulty: "easy",
    instructions: "Mix ingredients, bake until fudgy.",
    tags: ["dessert", "sweet", "baked"]
},
{
  id: "rec_112",
  name: "Masala Dosa",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 35,
  ingredients: ["rice batter", "potato", "onion", "spices", "oil"],
  difficulty: "medium",
  instructions: "Prepare dosa batter, cook dosa, fill with potato masala.",
  tags: ["breakfast", "south-indian", "classic"]
},
{
  id: "rec_113",
  name: "Chole Bhature",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 45,
  ingredients: ["chickpeas", "flour", "spices", "tomato", "oil"],
  difficulty: "medium",
  instructions: "Cook chickpeas with spices, fry bhature, serve hot.",
  tags: ["streetfood", "heavy", "punjabi"]
},
{
  id: "rec_114",
  name: "Egg Fried Rice",
  cuisine: "Chinese",
  isVegetarian: false,
  prepTimeMinutes: 20,
  ingredients: ["rice", "egg", "soy sauce", "peas", "spring onion"],
  difficulty: "easy",
  instructions: "Scramble eggs, add rice, mix with sauces and vegetables.",
  tags: ["quick", "lunch", "fried"]
},
{
  id: "rec_115",
  name: "Shahi Paneer",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 40,
  ingredients: ["paneer", "cream", "tomato", "cashews", "spices"],
  difficulty: "medium",
  instructions: "Blend cashews, cook gravy, add paneer and simmer.",
  tags: ["creamy", "dinner", "north-indian"]
},
{
  id: "rec_116",
  name: "Tandoori Chicken",
  cuisine: "Indian",
  isVegetarian: false,
  prepTimeMinutes: 50,
  ingredients: ["chicken", "yogurt", "tandoori masala", "lemon"],
  difficulty: "medium",
  instructions: "Marinate chicken, bake or grill until charred.",
  tags: ["spicy", "grilled", "starter"]
},
{
  id: "rec_117",
  name: "Pav Bhaji",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 30,
  ingredients: ["potato", "tomato", "butter", "spices", "pav buns"],
  difficulty: "easy",
  instructions: "Mash veggies, cook with spices, serve with buttered pav.",
  tags: ["streetfood", "buttery", "snack"]
},
{
  id: "rec_118",
  name: "Idli Sambhar",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 30,
  ingredients: ["rice batter", "dal", "veggies", "spices"],
  difficulty: "easy",
  instructions: "Steam idlis, prepare sambhar, serve hot.",
  tags: ["breakfast", "south-indian", "healthy"]
},
{
  id: "rec_119",
  name: "Caesar Salad",
  cuisine: "American",
  isVegetarian: false,
  prepTimeMinutes: 15,
  ingredients: ["lettuce", "chicken", "croutons", "parmesan", "dressing"],
  difficulty: "easy",
  instructions: "Mix all ingredients with dressing and serve.",
  tags: ["salad", "light", "healthy"]
},
{
  id: "rec_120",
  name: "Ramen Bowl",
  cuisine: "Japanese",
  isVegetarian: false,
  prepTimeMinutes: 35,
  ingredients: ["noodles", "egg", "broth", "pork", "soy sauce"],
  difficulty: "medium",
  instructions: "Prepare broth, cook noodles, add toppings.",
  tags: ["soup", "comfort", "authentic"]
},
{
  id: "rec_121",
  name: "French Toast",
  cuisine: "French",
  isVegetarian: true,
  prepTimeMinutes: 15,
  ingredients: ["bread", "egg", "milk", "sugar", "butter"],
  difficulty: "easy",
  instructions: "Dip bread in egg mixture and toast in butter.",
  tags: ["breakfast", "sweet", "quick"]
},
{
  id: "rec_122",
  name: "Fish Curry",
  cuisine: "Indian",
  isVegetarian: false,
  prepTimeMinutes: 40,
  ingredients: ["fish", "coconut", "spices", "onion"],
  difficulty: "medium",
  instructions: "Cook fish in coconut-based curry.",
  tags: ["seafood", "spicy", "coastal"]
},
{
  id: "rec_123",
  name: "Biryani",
  cuisine: "Indian",
  isVegetarian: false,
  prepTimeMinutes: 60,
  ingredients: ["rice", "chicken", "spices", "yogurt", "onion"],
  difficulty: "hard",
  instructions: "Layer rice and chicken, cook on dum for flavors.",
  tags: ["festive", "spicy", "classic"]
},
{
  id: "rec_124",
  name: "Veg Biryani",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 50,
  ingredients: ["rice", "vegetables", "spices", "curd", "mint"],
  difficulty: "medium",
  instructions: "Layer rice and vegetables, cook on dum.",
  tags: ["vegetarian", "aromatic", "dinner"]
},
{
  id: "rec_125",
  name: "Miso Soup",
  cuisine: "Japanese",
  isVegetarian: true,
  prepTimeMinutes: 10,
  ingredients: ["miso paste", "tofu", "seaweed", "spring onion"],
  difficulty: "easy",
  instructions: "Mix miso paste into hot water and add ingredients.",
  tags: ["soup", "light", "healthy"]
},
{
  id: "rec_126",
  name: "Grilled Cheese Sandwich",
  cuisine: "American",
  isVegetarian: true,
  prepTimeMinutes: 10,
  ingredients: ["bread", "cheese", "butter"],
  difficulty: "easy",
  instructions: "Butter bread, add cheese, grill until golden.",
  tags: ["snack", "cheesy", "quick"]
},
{
  id: "rec_127",
  name: "Beetroot Salad",
  cuisine: "Mediterranean",
  isVegetarian: true,
  prepTimeMinutes: 20,
  ingredients: ["beetroot", "olive oil", "feta", "salt"],
  difficulty: "easy",
  instructions: "Boil beetroot and mix with other ingredients.",
  tags: ["healthy", "light", "salad"]
},
{
  id: "rec_128",
  name: "Butter Chicken",
  cuisine: "Indian",
  isVegetarian: false,
  prepTimeMinutes: 45,
  ingredients: ["chicken", "butter", "tomato", "cream", "spices"],
  difficulty: "medium",
  instructions: "Cook grilled chicken in buttery tomato sauce.",
  tags: ["creamy", "rich", "north-indian"]
},
{
  id: "rec_129",
  name: "Aloo Paratha",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 25,
  ingredients: ["wheat flour", "potatoes", "spices", "ghee"],
  difficulty: "medium",
  instructions: "Stuff dough with potato mix and cook on tawa.",
  tags: ["breakfast", "stuffed", "classic"]
},
{
  id: "rec_130",
  name: "Tomato Soup",
  cuisine: "Continental",
  isVegetarian: true,
  prepTimeMinutes: 20,
  ingredients: ["tomatoes", "cream", "butter", "salt"],
  difficulty: "easy",
  instructions: "Boil tomatoes, blend, and simmer with spices.",
  tags: ["soup", "warm", "comfort"]
},
{
  id: "rec_131",
  name: "Hyderabadi Haleem",
  cuisine: "Indian",
  isVegetarian: false,
  prepTimeMinutes: 120,
  ingredients: ["meat", "lentils", "wheat", "spices"],
  difficulty: "hard",
  instructions: "Slow-cook mixture until paste-like consistency.",
  tags: ["festive", "rich", "protein"]
},
{
  id: "rec_132",
  name: "Mango Shake",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 5,
  ingredients: ["mango", "milk", "sugar", "ice"],
  difficulty: "easy",
  instructions: "Blend everything until smooth.",
  tags: ["drink", "summer", "sweet"]
},
{
  id: "rec_133",
  name: "Chocolate Ice Cream",
  cuisine: "Dessert",
  isVegetarian: true,
  prepTimeMinutes: 15,
  ingredients: ["milk", "cocoa", "cream", "sugar"],
  difficulty: "easy",
  instructions: "Mix and freeze until solid.",
  tags: ["dessert", "cold", "chocolate"]
},
{
  id: "rec_134",
  name: "Garlic Noodles",
  cuisine: "Asian",
  isVegetarian: true,
  prepTimeMinutes: 20,
  ingredients: ["noodles", "garlic", "soy sauce", "spring onion"],
  difficulty: "easy",
  instructions: "Stir-fry garlic, add noodles and sauces.",
  tags: ["quick", "flavorful", "snack"]
},
{
  id: "rec_135",
  name: "BBQ Wings",
  cuisine: "American",
  isVegetarian: false,
  prepTimeMinutes: 40,
  ingredients: ["chicken wings", "bbq sauce", "salt"],
  difficulty: "easy",
  instructions: "Bake wings and coat with BBQ sauce.",
  tags: ["starter", "spicy", "party"]
},
{
  id: "rec_136",
  name: "Veg Sandwich",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 10,
  ingredients: ["bread", "cucumber", "tomato", "butter"],
  difficulty: "easy",
  instructions: "Assemble veggies between buttered bread slices.",
  tags: ["snack", "simple", "quick"]
},
{
  id: "rec_137",
  name: "Chicken Momos",
  cuisine: "Tibetan",
  isVegetarian: false,
  prepTimeMinutes: 35,
  ingredients: ["chicken", "flour", "spices"],
  difficulty: "medium",
  instructions: "Fill dough with chicken and steam.",
  tags: ["dumplings", "streetfood", "snack"]
},
{
  id: "rec_138",
  name: "Veg Momos",
  cuisine: "Tibetan",
  isVegetarian: true,
  prepTimeMinutes: 30,
  ingredients: ["cabbage", "carrot", "flour", "spices"],
  difficulty: "medium",
  instructions: "Fill dough with veggies and steam.",
  tags: ["vegetarian", "snack", "streetfood"]
},
{
  id: "rec_139",
  name: "Falooda",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 20,
  ingredients: ["vermicelli", "milk", "rose syrup", "ice cream"],
  difficulty: "easy",
  instructions: "Layer ingredients in a glass and serve chilled.",
  tags: ["dessert", "cold", "sweet"]
},
{
  id: "rec_140",
  name: "Cheeseburger",
  cuisine: "American",
  isVegetarian: false,
  prepTimeMinutes: 20,
  ingredients: ["beef patty", "bun", "cheese", "lettuce"],
  difficulty: "easy",
  instructions: "Grill patty, assemble burger with toppings.",
  tags: ["fastfood", "cheesy", "heavy"]
},
{
  id: "rec_141",
  name: "Samosa",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 25,
  ingredients: ["potato", "peas", "flour", "spices"],
  difficulty: "medium",
  instructions: "Stuff dough and deep-fry until golden.",
  tags: ["snack", "fried", "streetfood"]
},
{
  id: "rec_142",
  name: "Mushroom Soup",
  cuisine: "Continental",
  isVegetarian: true,
  prepTimeMinutes: 30,
  ingredients: ["mushroom", "cream", "garlic", "butter"],
  difficulty: "easy",
  instructions: "Cook mushrooms and blend with cream.",
  tags: ["soup", "warm", "creamy"]
},
{
  id: "rec_143",
  name: "Paneer Tikka",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 35,
  ingredients: ["paneer", "yogurt", "spices", "lemon"],
  difficulty: "medium",
  instructions: "Marinate paneer and grill until charred.",
  tags: ["starter", "spicy", "tandoor"]
},
{
  id: "rec_144",
  name: "Greek Yogurt Bowl",
  cuisine: "Greek",
  isVegetarian: true,
  prepTimeMinutes: 5,
  ingredients: ["yogurt", "honey", "berries", "granola"],
  difficulty: "easy",
  instructions: "Mix everything in a bowl and serve.",
  tags: ["breakfast", "healthy", "sweet"]
},
{
  id: "rec_145",
  name: "Pasta Alfredo",
  cuisine: "Italian",
  isVegetarian: true,
  prepTimeMinutes: 25,
  ingredients: ["pasta", "cream", "butter", "parmesan"],
  difficulty: "easy",
  instructions: "Cook pasta and mix with creamy Alfredo sauce.",
  tags: ["creamy", "cheesy", "italian"]
},
{
  id: "rec_146",
  name: "Chicken Alfredo",
  cuisine: "Italian",
  isVegetarian: false,
  prepTimeMinutes: 30,
  ingredients: ["pasta", "cream", "chicken", "butter"],
  difficulty: "easy",
  instructions: "Cook pasta, sauté chicken, mix with Alfredo sauce.",
  tags: ["creamy", "chicken", "dinner"]
},
{
  id: "rec_147",
  name: "Masala Tea",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 10,
  ingredients: ["milk", "tea leaves", "spices", "sugar"],
  difficulty: "easy",
  instructions: "Boil everything and strain.",
  tags: ["drink", "warm", "classic"]
},
{
  id: "rec_148",
  name: "Cold Coffee",
  cuisine: "Beverage",
  isVegetarian: true,
  prepTimeMinutes: 5,
  ingredients: ["coffee", "milk", "ice", "sugar"],
  difficulty: "easy",
  instructions: "Blend all ingredients.",
  tags: ["drink", "cold", "refreshing"]
},
{
  id: "rec_149",
  name: "Chicken Curry",
  cuisine: "Indian",
  isVegetarian: false,
  prepTimeMinutes: 40,
  ingredients: ["chicken", "onion", "tomato", "spices"],
  difficulty: "medium",
  instructions: "Cook chicken in onion-tomato gravy.",
  tags: ["spicy", "dinner", "classic"]
},
{
  id: "rec_150",
  name: "Fried Chicken",
  cuisine: "American",
  isVegetarian: false,
  prepTimeMinutes: 30,
  ingredients: ["chicken", "flour", "spices", "oil"],
  difficulty: "easy",
  instructions: "Coat chicken in flour and deep-fry.",
  tags: ["crispy", "fried", "fastfood"]
},
{
  id: "rec_151",
  name: "Penne Arrabbiata",
  cuisine: "Italian",
  isVegetarian: true,
  prepTimeMinutes: 20,
  ingredients: ["pasta", "tomato", "chilli flakes", "garlic"],
  difficulty: "easy",
  instructions: "Cook pasta and mix with spicy tomato sauce.",
  tags: ["spicy", "italian", "easy"]
},
{
  id: "rec_152",
  name: "Veg Pulao",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 25,
  ingredients: ["rice", "vegetables", "spices"],
  difficulty: "easy",
  instructions: "Cook rice with vegetables and spices.",
  tags: ["quick", "flavorful", "dinner"]
},
{
  id: "rec_153",
  name: "Chicken Sandwich",
  cuisine: "American",
  isVegetarian: false,
  prepTimeMinutes: 15,
  ingredients: ["bread", "chicken", "mayo", "lettuce"],
  difficulty: "easy",
  instructions: "Mix chicken with mayo and assemble sandwich.",
  tags: ["snack", "quick", "lunch"]
},
{
  id: "rec_154",
  name: "Veg Pizza",
  cuisine: "Italian",
  isVegetarian: true,
  prepTimeMinutes: 30,
  ingredients: ["dough", "sauce", "cheese", "vegetables"],
  difficulty: "medium",
  instructions: "Top dough with veggies and bake.",
  tags: ["baked", "cheesy", "italian"]
},
{
  id: "rec_155",
  name: "Dal Tadka",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 25,
  ingredients: ["dal", "ghee", "garlic", "spices"],
  difficulty: "easy",
  instructions: "Cook dal and add ghee tadka.",
  tags: ["comfort", "simple", "veg"]
},
{
  id: "rec_156",
  name: "Rajma Chawal",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 45,
  ingredients: ["rajma", "rice", "tomato", "spices"],
  difficulty: "medium",
  instructions: "Cook rajma curry and serve with rice.",
  tags: ["north-indian", "classic", "comfort"]
},
{
  id: "rec_157",
  name: "Steamed Dhokla",
  cuisine: "Indian",
  isVegetarian: true,
  prepTimeMinutes: 20,
  ingredients: ["gram flour", "curd", "salt", "spices"],
  difficulty: "easy",
  instructions: "Steam batter and temper with mustard seeds.",
  tags: ["snack", "light", "gujarati"]
},
{
  id: "rec_158",
  name: "Tacos",
  cuisine: "Mexican",
  isVegetarian: false,
  prepTimeMinutes: 25,
  ingredients: ["tortilla", "meat", "cheese", "lettuce"],
  difficulty: "easy",
  instructions: "Fill tortillas with cooked meat and veggies.",
  tags: ["mexican", "streetfood", "party"]
},
{
  id: "rec_159",
  name: "Veg Tacos",
  cuisine: "Mexican",
  isVegetarian: true,
  prepTimeMinutes: 20,
  ingredients: ["tortilla", "beans", "cheese", "salsa"],
  difficulty: "easy",
  instructions: "Fill tortillas with beans and veggies.",
  tags: ["vegetarian", "mexican", "snack"]
},
{
  id: "rec_160",
  name: "Strawberry Milkshake",
  cuisine: "Beverage",
  isVegetarian: true,
  prepTimeMinutes: 5,
  ingredients: ["strawberries", "milk", "sugar", "ice"],
  difficulty: "easy",
  instructions: "Blend all ingredients.",
  tags: ["drink", "sweet", "cold"]
},
{
  id: "rec_161",
  name: "Fruit Salad",
  cuisine: "Continental",
  isVegetarian: true,
  prepTimeMinutes: 10,
  ingredients: ["apple", "banana", "grapes", "honey"],
  difficulty: "easy",
  instructions: "Mix all chopped fruits with honey.",
  tags: ["healthy", "light", "summer"]
}

];
export default SampleRecipes;